name: smashlibs
description: Libs and utilities used by the SMASH digital field mapping project.

# Copyright (c) 2019-2020. www.hydrologis.com. All rights reserved.
# Use of this source code is governed by a GPL3 license that can be
# found in the LICENSE file.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ##################
  # OWN
  #################

  #BSD
  dart_jts: ^0.0.7
    # path: ../dart_jts/
  #    git:
  #      url: https://github.com/moovida/dart_jts.git

  dart_hydrologis_utils: ^0.5.4
    # path: ../dart_hydrologis_utils/

  ####################
  # OTHERS
  ####################
  # BSD
  # charset_converter: ^1.0.3
  # MIT
  material_design_icons_flutter: ^4.0.5345
  # MIT
  share_extend: ^1.1.2
  # BSD
  path_provider: ^1.6.5
  # MIT
  path_provider_ex: ^1.0.1
  # MIT
  proj4dart: ^1.0.4
  # MIT
  dio: ">=3.0.9 <6.0.0"
  # MIT
  permission_handler: ^5.1.0
    # git: 
    #   url: https://github.com/Baseflow/flutter-permission-handler.git
    #   path: permission_handler

  # BSD
  device_info: ^0.4.2+1
  # MIT
  after_layout: ^1.0.7+2

  # BSD
  url_launcher: ^5.4.2

  # MIT
  flutter_tags: ^0.4.8

  # MIT
  flutter_material_pickers: #^1.9.2
    git:
      url: https://github.com/moovida/flutter_material_pickers.git
      ref: 74bf310

  # BSD
  shared_preferences: ^0.5.6+3
  # MIT
  screen: 0.0.5
  # ON ANDROID NEEDS:
  # <uses-permission android:name="android.permission.WAKE_LOCK" />

  #BSD
  image_picker: ^0.6.4
  # ON IOS NEEDS:
  #  <key>NSPhotoLibraryUsageDescription</key>
  #  <string>The app needs to access the photo library to attach media to the survey.</string>
  #  <key>NSCameraUsageDescription</key>
  #  <string>The app needs to use the camera to take picture notes during the field mapping activity.</string>
  #  <key>NSMicrophoneUsageDescription</key>
  #  <string>The app needs to use the camera to take vocal notes during the field mapping activity.</string>

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
